### ISSUE TITLE
Default value for `length` prop

### ISSUE THREAD

**Issue by gsalisi** [u-wave/react-list-lazy-load#21]
Some (if not most) paginated list have indeterminate "total" page length and only relies on the emptiness of the `next` page to decide whether its the end of the list.

In my usage, i find that length=`Number.POSITIVE_INFINITY` did the trick.

Would this work as a default value?

**Comment by goto-bus-stop** [comment]
I don't think that would work with this implementation. react-list-lazy-load needs to know the amount of items so it can show a scrollbar of the correct size and such. Infinite scroll IMO belongs in a different component, I think it would require quite a different implementation than react-list-lazy-load uses.
