### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Azumi0** [u-wave/react-list-lazy-load#4]
Hi,
First of all I would like to thank you for making this awesome component!

Now let's get to business: Sometimes (at random, but frequently) my console if full of errors made by LazyList
```
Uncaught TypeError: Cannot read property 'getVisibleRange' of null
    at LazyList.(anonymous function) [as getVisibleRange] (http://localhost/dist/bundle.js:63022:40)
    at LazyList.updateFrame (http://localhost/dist/bundle.js:62942:33)
LazyList.(anonymous function) @ bundle.js:63022
updateFrame @ bundle.js:62942
```

The error seems to appear onScroll.
I am using this versions of components:
```
"react": "^15.6.1",
"react-dom": "^15.6.1",
"react-list": "^0.8.6",
"react-list-lazy-load": "^1.0.5",
```

Any help would be very appreciated, thanks!

**Comment by goto-bus-stop** [comment]
Hi, sorry for the delay, I was on vacation :)

That error suggests the `ref` that react-list-lazy-load places on the react-list is not available. I'm not sure why that would happen, can you share a snippet that reproduces the issue?

**Comment by ArtemUstilov** [comment]
```
<LazyLoading
        length={objectsTotal}
        loadMargin={10}
        pageSize={10}
        items={objects}
        onRequestPage={this.onRequestPage}
      >
        <ReactList
          itemRenderer={(idx, key) => {
            return (
                <ObjectItem
                  object={idx < objects.length ? objects[idx] : null}
                  key={idx}
                  history={history}
                  attributes={attributes}
                />
            )
          }}
          type="simple"
          length={objectsTotal}
        /> </LazyLoading>
```
this is my example of code
I am using react routers to switch between pages and this error appears every time I switch to other page and then return to page with list

**Comment by ArtemUstilov** [comment]
@goto-bus-stop

**Comment by fesaza** [comment]
In  my case I got that error when I had a conditional rendering for the lazy list component. The error started to display on the second time I rendered it. I don't know if you might have something similar. But I fixed it changing that conditional rendering
